version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  commands:
    - mamba install -c conda-forge -c nodefaults pixi==0.39.0
    - pixi run readthedocs
sphinx:
  configuration: docs/conf.py
formats:
- pdf