{% set name = "gaitalytics" %}
{% set version = '0.2.1.post3' %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DART-Lab-LLUI/python-gaitalytics/releases/download/{{ version }}/gaitalytics-{{ version }}.tar.gz

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - pip
    - python >=3.11
    - setuptools >=64
    - setuptools_scm >=8
  host:
    - python >=3.11
    - setuptools >=64
    - setuptools_scm >=8
    - pip
  run:
    - python >=3.11
    - h5netcdf >=1.3.0
    - pandas >=1.5
    - pyyaml >=6.0.1
    - scipy >=1.13
    - numpy >=1.23
    - xarray >=2024.6.0
    - pyomeca >=2024.0.2
    - ezc3d >=1.5.17,*=*python*

test:
  source_files:
    - tests/
  imports:
    - gaitalytics
  commands:
    - pip check
    - pytest tests/test_api.py
  requires:
    - pip
    - pytest


about:
  home: https://github.com/DART-Lab-LLUI/python-gaitalytics
  summary: This library provides tools to analyze motion capture data.
  license: MIT
  license_family: MIT
  dev_url: https://github.com/DART-Lab-LLUI/python-gaitalytics
  doc_url: https://python-gaitalytics.readthedocs.io

extra:
  recipe-maintainers:
    - anboen
